import { User, Video, Story, StoryPost, Conversation, Gift, Ad, Comment, Short, Notification, ProUser } from '@/types';

export const MOCK_USERS: User[] = [
  {
    id: '1',
    username: 'emma_creates',
    email: 'emma@viral.app',
    avatar: 'https://i.pravatar.cc/150?img=1',
    bio: 'Content creator | Fashion & Lifestyle',
    isVerified: true,
    isMinor: false,
    followers: 125000,
    following: 342,
    totalViews: 5600000,
    createdAt: new Date(Date.now() - 365 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '2',
    username: 'alex_vibes',
    email: 'alex@viral.app',
    avatar: 'https://i.pravatar.cc/150?img=12',
    bio: 'Music & Dance',
    isVerified: false,
    isMinor: false,
    followers: 45000,
    following: 189,
    totalViews: 1200000,
    createdAt: new Date(Date.now() - 180 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const MOCK_CURRENT_USER: User = {
  id: 'current',
  username: 'you',
  email: 'you@viral.app',
  avatar: 'https://i.pravatar.cc/150?img=50',
  bio: 'Living my best life',
  isVerified: false,
  isMinor: false,
  followers: 1250,
  following: 456,
  totalViews: 25600,
  createdAt: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
};

export const MOCK_VIDEOS: Video[] = [
  {
    id: '1',
    userId: '1',
    user: MOCK_USERS[0],
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330',
    caption: 'Summer vibes ☀️ #fashion #ootd',
    soundName: 'Summer Days',
    soundAuthor: 'Chill Beats',
    likes: 12500,
    comments: 234,
    shares: 89,
    views: 125000,
    isLiked: false,
    location: 'Los Angeles, CA',
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    expiresAt: new Date(Date.now() + 22 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '2',
    userId: '2',
    user: MOCK_USERS[1],
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d',
    caption: 'New dance routine! 💃 Who can do this?',
    soundName: 'Viral Beat',
    soundAuthor: 'DJ Pulse',
    likes: 8900,
    comments: 156,
    shares: 45,
    views: 89000,
    isLiked: true,
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    expiresAt: new Date(Date.now() + 19 * 60 * 60 * 1000).toISOString(),
  },
];

export const MOCK_STORIES: Story[] = [
  {
    id: '1',
    userId: '1',
    user: MOCK_USERS[0],
    imageUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330',
    isLive: false,
    postCount: 3,
    dominantColor: '#E53935',
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    expiresAt: new Date(Date.now() + 23 * 60 * 60 * 1000).toISOString(),
    isViewed: false,
  },
  {
    id: '2',
    userId: '2',
    user: MOCK_USERS[1],
    imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d',
    isLive: true,
    viewerCount: 1234,
    postCount: 2,
    dominantColor: '#1E88E5',
    createdAt: new Date(Date.now() - 0.5 * 60 * 60 * 1000).toISOString(),
    expiresAt: new Date(Date.now() + 23.5 * 60 * 60 * 1000).toISOString(),
    isViewed: false,
  },
  {
    id: '3',
    userId: '1',
    user: MOCK_USERS[0],
    imageUrl: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e',
    isLive: false,
    postCount: 4,
    dominantColor: '#9C27B0',
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    expiresAt: new Date(Date.now() + 22 * 60 * 60 * 1000).toISOString(),
    isViewed: false,
  },
  {
    id: '4',
    userId: '2',
    user: MOCK_USERS[1],
    imageUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80',
    isLive: false,
    postCount: 2,
    dominantColor: '#FF9800',
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    expiresAt: new Date(Date.now() + 21 * 60 * 60 * 1000).toISOString(),
    isViewed: false,
  },
  {
    id: '5',
    userId: '1',
    user: MOCK_USERS[0],
    imageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb',
    isLive: false,
    postCount: 1,
    dominantColor: '#00BCD4',
    createdAt: new Date(Date.now() - 23 * 60 * 60 * 1000).toISOString(),
    expiresAt: new Date(Date.now() + 30 * 60 * 1000).toISOString(),
    isViewed: false,
  },
];

export const MOCK_STORY_POSTS: StoryPost[] = [
  {
    id: 'sp1',
    storyId: '1',
    type: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=1080',
    caption: 'Starting my day with good vibes ✨',
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    isViewed: false,
  },
  {
    id: 'sp2',
    storyId: '1',
    type: 'video',
    mediaUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    caption: 'Check out this amazing view! 🌅',
    duration: 8000,
    createdAt: new Date(Date.now() - 55 * 60 * 1000).toISOString(),
    isViewed: false,
  },
  {
    id: 'sp3',
    storyId: '1',
    type: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=1080',
    caption: 'Fashion moment 👗',
    createdAt: new Date(Date.now() - 50 * 60 * 1000).toISOString(),
    isViewed: false,
  },
  {
    id: 'sp4',
    storyId: '2',
    type: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=1080',
    caption: 'Live from the studio! 🎤',
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    isViewed: false,
  },
  {
    id: 'sp5',
    storyId: '2',
    type: 'video',
    mediaUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    caption: 'New dance moves 💃',
    duration: 10000,
    createdAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    isViewed: false,
  },
  {
    id: 'sp6',
    storyId: '3',
    type: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=1080',
    caption: 'Coffee time ☕',
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    isViewed: false,
  },
  {
    id: 'sp7',
    storyId: '3',
    type: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=1080',
    caption: 'Selfie time 📸',
    createdAt: new Date(Date.now() - 1.9 * 60 * 60 * 1000).toISOString(),
    isViewed: false,
  },
  {
    id: 'sp8',
    storyId: '3',
    type: 'video',
    mediaUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    caption: 'Having fun! 🎉',
    duration: 6000,
    createdAt: new Date(Date.now() - 1.8 * 60 * 60 * 1000).toISOString(),
    isViewed: false,
  },
  {
    id: 'sp9',
    storyId: '3',
    type: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=1080',
    caption: 'Outfit check ✨',
    createdAt: new Date(Date.now() - 1.7 * 60 * 60 * 1000).toISOString(),
    isViewed: false,
  },
  {
    id: 'sp10',
    storyId: '4',
    type: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=1080',
    caption: 'Golden hour 🌅',
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    isViewed: false,
  },
  {
    id: 'sp11',
    storyId: '4',
    type: 'image',
    mediaUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=1080',
    caption: 'Feeling good today 💫',
    createdAt: new Date(Date.now() - 2.9 * 60 * 60 * 1000).toISOString(),
    isViewed: false,
  },
];

export const MOCK_CHAT_CONVERSATIONS = [
  {
    id: '1',
    user: {
      id: '1',
      name: 'Dani',
      avatar: 'https://i.pravatar.cc/150?img=1',
    },
    lastMessage: {
      id: '1',
      type: 'shot' as const,
      text: 'New Shot and chat',
      timestamp: '45s',
    },
    unreadCount: 12,
    hasStory: true,
  },
  {
    id: '2',
    user: {
      id: '2',
      name: 'Rachel',
      avatar: 'https://i.pravatar.cc/150?img=5',
    },
    lastMessage: {
      id: '2',
      type: 'video' as const,
      text: 'New Video',
      timestamp: '1h',
    },
    unreadCount: 12,
    hasStory: true,
  },
  {
    id: '3',
    user: {
      id: '3',
      name: 'Alex',
      avatar: 'https://i.pravatar.cc/150?img=12',
    },
    lastMessage: {
      id: '3',
      type: 'message' as const,
      text: 'New Message',
      timestamp: '1d',
    },
    unreadCount: 12,
    hasStory: false,
  },
  {
    id: '4',
    user: {
      id: '4',
      name: 'Dani',
      avatar: 'https://i.pravatar.cc/150?img=1',
    },
    lastMessage: {
      id: '4',
      type: 'shot' as const,
      text: 'Tap to chat',
      timestamp: '',
    },
    unreadCount: 12,
    hasStory: false,
  },
  {
    id: '5',
    user: {
      id: '5',
      name: 'Coca Cola',
      avatar: 'https://images.unsplash.com/photo-1554866585-cd94860890b7?w=150&h=150&fit=crop',
      isBrand: true,
    },
    lastMessage: {
      id: '5',
      type: 'ad' as const,
      text: 'Tap to see the exclusive Ad',
      timestamp: '',
    },
    unreadCount: 12,
    hasStory: false,
  },
  {
    id: '6',
    user: {
      id: '6',
      name: 'Rachel',
      avatar: 'https://i.pravatar.cc/150?img=5',
    },
    lastMessage: {
      id: '6',
      type: 'shot' as const,
      text: 'Tap to reply',
      timestamp: '',
    },
    unreadCount: 12,
    hasStory: false,
  },
  {
    id: '7',
    user: {
      id: '7',
      name: 'Alex',
      avatar: 'https://i.pravatar.cc/150?img=12',
    },
    lastMessage: {
      id: '7',
      type: 'message' as const,
      text: 'Tap to chat',
      timestamp: '',
    },
    unreadCount: 12,
    hasStory: false,
  },
];

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: '1',
    user: MOCK_USERS[0],
    lastMessage: {
      id: '1',
      senderId: '1',
      receiverId: 'current',
      text: 'Hey! Love your latest video 🔥',
      createdAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
      isRead: false,
    },
    unreadCount: 2,
  },
  {
    id: '2',
    user: MOCK_USERS[1],
    lastMessage: {
      id: '2',
      senderId: 'current',
      receiverId: '2',
      text: 'Thanks for the collab!',
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
      isRead: true,
    },
    unreadCount: 0,
  },
];

export const MOCK_GIFTS: Gift[] = [
  { id: '1', name: 'Rose', icon: '🌹', price: 1, animationUrl: '' },
  { id: '2', name: 'Heart', icon: '❤️', price: 5, animationUrl: '' },
  { id: '3', name: 'Fire', icon: '🔥', price: 10, animationUrl: '' },
  { id: '4', name: 'Diamond', icon: '💎', price: 50, animationUrl: '' },
  { id: '5', name: 'Crown', icon: '👑', price: 100, animationUrl: '' },
];

export const MOCK_ADS: Ad[] = [
  {
    id: '1',
    brand: 'Nike',
    imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff',
    ctaText: 'Shop Now',
    ctaUrl: 'https://nike.com',
    impressions: 125000,
    clicks: 2500,
  },
  {
    id: '2',
    brand: 'Spotify',
    imageUrl: 'https://images.unsplash.com/photo-1614680376593-902f74cf0d41',
    ctaText: 'Listen Free',
    ctaUrl: 'https://spotify.com',
    impressions: 98000,
    clicks: 1890,
  },
  {
    id: '3',
    brand: 'Apple',
    imageUrl: 'https://images.unsplash.com/photo-1611472173362-3f53dbd65d80',
    ctaText: 'Learn More',
    ctaUrl: 'https://apple.com',
    impressions: 156000,
    clicks: 3200,
  },
];

export const CATEGORIES = [
  'All',
  'Dance',
  'Comedy',
  'Music',
  'Fashion',
  'Food',
  'Travel',
  'Sports',
  'Gaming',
  'DIY',
  'Pets',
];

export const MOCK_COMMENTS: Comment[] = [
  {
    id: '1',
    userId: '1',
    user: MOCK_USERS[0],
    videoId: '1',
    text: 'This is amazing! Love your style 🔥',
    likes: 234,
    isLiked: false,
    replies: [],
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '2',
    userId: '2',
    user: MOCK_USERS[1],
    videoId: '1',
    text: 'Incredible content! Keep it up 💪',
    likes: 89,
    isLiked: true,
    replies: [
      {
        id: '3',
        userId: 'current',
        user: MOCK_CURRENT_USER,
        videoId: '1',
        text: 'Thanks so much!',
        likes: 12,
        isLiked: false,
        replies: [],
        createdAt: new Date(Date.now() - 0.5 * 60 * 60 * 1000).toISOString(),
      },
    ],
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
];

export const REPORT_REASONS = [
  'Spam or misleading',
  'Harassment or bullying',
  'Hate speech',
  'Violence or dangerous content',
  'Nudity or sexual content',
  'Copyright violation',
  'Self-harm or suicide',
  'Other',
];

export const DISCOVER_CATEGORIES = [
  { id: '1', name: 'Technology', icon: '💻' },
  { id: '2', name: 'Politics', icon: '🏛️' },
  { id: '3', name: 'Sports', icon: '⚽' },
  { id: '4', name: 'Music', icon: '🎵' },
  { id: '5', name: 'Fashion', icon: '👗' },
  { id: '6', name: 'Food', icon: '🍔' },
  { id: '7', name: 'Travel', icon: '✈️' },
  { id: '8', name: 'Gaming', icon: '🎮' },
];

export const MOCK_SHORTS: Short[] = [
  {
    id: 's1',
    type: 'regular' as const,
    userId: '1',
    user: MOCK_USERS[0],
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330',
    caption: 'When the rain drops, it is Purple. 💜',
    tags: ['tag', 'tag', 'tag'],
    category: 'Jam Sessions',
    location: 'Los Angeles, CA',
    containsAI: true,
    soundName: 'Summer Days',
    soundAuthor: 'Chill Beats',
    likes: 8900,
    comments: 156,
    shares: 45,
    views: 12500,
    bookmarks: 75,
    isLiked: false,
    isBookmarked: false,
    likedBy: {
      user: MOCK_USERS[1],
      othersCount: 234,
    },
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 's2',
    type: 'regular' as const,
    userId: '2',
    user: MOCK_USERS[1],
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d',
    caption: 'New dance routine! Who can do this?',
    tags: ['dance', 'viral'],
    category: 'Dance',
    location: 'New York, NY',
    containsAI: false,
    soundName: 'Viral Beat',
    soundAuthor: 'DJ Pulse',
    likes: 5600,
    comments: 89,
    shares: 23,
    views: 8900,
    bookmarks: 45,
    isLiked: true,
    isBookmarked: true,
    likedBy: {
      user: MOCK_USERS[0],
      othersCount: 1200,
    },
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 's3',
    type: 'regular' as const,
    userId: '1',
    user: MOCK_USERS[0],
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e',
    caption: 'Weekend vibes are the best 🌴',
    tags: ['weekend', 'lifestyle'],
    category: 'Lifestyle',
    location: 'Miami, FL',
    soundName: 'Chill Vibes',
    soundAuthor: 'Lo-Fi Master',
    likes: 3400,
    comments: 67,
    shares: 12,
    views: 6700,
    bookmarks: 34,
    isLiked: false,
    isBookmarked: false,
    likedBy: {
      user: MOCK_USERS[1],
      othersCount: 567,
    },
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 's4',
    type: 'regular' as const,
    userId: '2',
    user: MOCK_USERS[1],
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80',
    caption: 'This is how you do it! Follow along 💪',
    tags: ['tutorial', 'howto'],
    category: 'Tutorial',
    location: 'Chicago, IL',
    containsAI: true,
    soundName: 'Upbeat Energy',
    soundAuthor: 'Energy FM',
    likes: 7800,
    comments: 123,
    shares: 34,
    views: 9800,
    bookmarks: 56,
    isLiked: false,
    isBookmarked: false,
    likedBy: {
      user: MOCK_USERS[0],
      othersCount: 890,
    },
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 's5-membership',
    type: 'membership' as const,
    userId: '1',
    user: MOCK_USERS[0],
    videoUrl: '',
    thumbnailUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1',
    caption: 'Exclusive content for members only',
    tags: ['exclusive', 'premium'],
    likes: 0,
    comments: 0,
    shares: 0,
    views: 0,
    bookmarks: 0,
    isLiked: false,
    isBookmarked: false,
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 's6',
    type: 'regular' as const,
    userId: '2',
    user: MOCK_USERS[1],
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb',
    caption: 'Behind the scenes of my latest shoot 📸',
    tags: ['bts', 'photography'],
    soundName: 'Studio Vibes',
    soundAuthor: 'Photo Gang',
    likes: 4500,
    comments: 78,
    shares: 19,
    views: 7200,
    bookmarks: 41,
    isLiked: false,
    isBookmarked: false,
    createdAt: new Date(Date.now() - 7 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 's7',
    type: 'regular' as const,
    userId: '1',
    user: MOCK_USERS[0],
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df',
    caption: 'Can you believe this view? 🌅',
    tags: ['sunset', 'nature'],
    soundName: 'Nature Sounds',
    soundAuthor: 'Ambient Collective',
    likes: 6200,
    comments: 94,
    shares: 28,
    views: 8500,
    bookmarks: 52,
    isLiked: true,
    isBookmarked: false,
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 's8',
    type: 'regular' as const,
    userId: '2',
    user: MOCK_USERS[1],
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2',
    caption: 'Quick makeup tutorial for beginners ✨',
    tags: ['makeup', 'beauty'],
    soundName: 'Beauty Beat',
    soundAuthor: 'Glam Squad',
    likes: 9100,
    comments: 167,
    shares: 56,
    views: 11200,
    bookmarks: 89,
    isLiked: false,
    isBookmarked: true,
    createdAt: new Date(Date.now() - 9 * 60 * 60 * 1000).toISOString(),
  },

  {
    id: 's9',
    type: 'regular' as const,
    userId: '1',
    user: MOCK_USERS[0],
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9',
    caption: 'Morning routine that changed my life 🌞',
    tags: ['morning', 'routine'],
    soundName: 'Morning Motivation',
    soundAuthor: 'Wellness Sounds',
    likes: 5400,
    comments: 102,
    shares: 31,
    views: 8100,
    bookmarks: 67,
    isLiked: false,
    isBookmarked: false,
    createdAt: new Date(Date.now() - 9 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 's10',
    type: 'regular' as const,
    userId: '2',
    user: MOCK_USERS[1],
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1520813792240-56fc4a3765a7',
    caption: 'Best workout moves for summer body 💪',
    tags: ['fitness', 'workout'],
    soundName: 'Gym Energy',
    soundAuthor: 'Fitness Beats',
    likes: 7600,
    comments: 134,
    shares: 45,
    views: 9900,
    bookmarks: 78,
    isLiked: true,
    isBookmarked: false,
    createdAt: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 's11',
    type: 'regular' as const,
    userId: '1',
    user: MOCK_USERS[0],
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f',
    caption: 'Styling tips you need to know 👗',
    tags: ['fashion', 'tips'],
    soundName: 'Fashion Forward',
    soundAuthor: 'Style Icons',
    likes: 4800,
    comments: 87,
    shares: 22,
    views: 7500,
    bookmarks: 43,
    isLiked: false,
    isBookmarked: false,
    createdAt: new Date(Date.now() - 11 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 's12',
    type: 'regular' as const,
    userId: '2',
    user: MOCK_USERS[1],
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1502823403499-6ccfcf4fb453',
    caption: 'Travel vlog: exploring hidden gems 🗺️',
    tags: ['travel', 'explore'],
    soundName: 'Wanderlust',
    soundAuthor: 'Travel Tunes',
    likes: 6800,
    comments: 112,
    shares: 38,
    views: 9100,
    bookmarks: 61,
    isLiked: false,
    isBookmarked: true,
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 's13-membership',
    type: 'membership' as const,
    userId: '1',
    user: MOCK_USERS[0],
    videoUrl: '',
    thumbnailUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d',
    caption: 'Premium members only content',
    tags: ['exclusive', 'vip'],
    likes: 0,
    comments: 0,
    shares: 0,
    views: 0,
    bookmarks: 0,
    isLiked: false,
    isBookmarked: false,
    createdAt: new Date(Date.now() - 13 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 's14',
    type: 'regular' as const,
    userId: '2',
    user: MOCK_USERS[1],
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1499952127939-9bbf5af6c51c',
    caption: 'Cooking the perfect pasta 🍝',
    tags: ['cooking', 'food'],
    soundName: 'Kitchen Groove',
    soundAuthor: 'Chef Beats',
    likes: 5900,
    comments: 98,
    shares: 27,
    views: 8400,
    bookmarks: 54,
    isLiked: false,
    isBookmarked: false,
    createdAt: new Date(Date.now() - 14 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 's15',
    type: 'regular' as const,
    userId: '1',
    user: MOCK_USERS[0],
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1',
    caption: 'DIY home decor on a budget 🏠',
    tags: ['diy', 'homedecor'],
    soundName: 'Creative Flow',
    soundAuthor: 'DIY Squad',
    likes: 4200,
    comments: 76,
    shares: 18,
    views: 6900,
    bookmarks: 39,
    isLiked: false,
    isBookmarked: false,
    createdAt: new Date(Date.now() - 15 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 's16',
    type: 'regular' as const,
    userId: '2',
    user: MOCK_USERS[1],
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04',
    caption: 'My daily skincare routine ✨',
    tags: ['skincare', 'selfcare'],
    soundName: 'Glow Up',
    soundAuthor: 'Beauty Vibes',
    likes: 8300,
    comments: 145,
    shares: 49,
    views: 10500,
    bookmarks: 82,
    isLiked: true,
    isBookmarked: false,
    createdAt: new Date(Date.now() - 16 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 's17-ad',
    type: 'ad' as const,
    userId: 'brand-nike',
    user: {
      id: 'brand-nike',
      username: 'nike',
      email: 'contact@nike.com',
      avatar: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff',
      bio: 'Just Do It',
      isVerified: true,
      isMinor: false,
      followers: 5000000,
      following: 0,
      totalViews: 0,
      createdAt: new Date().toISOString(),
    },
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff',
    caption: 'New collection is here! Shop now',
    tags: ['sponsored', 'ad'],
    likes: 0,
    comments: 0,
    shares: 0,
    views: 125000,
    bookmarks: 0,
    isLiked: false,
    isBookmarked: false,
    adDuration: 15000,
    adMinViewTime: 2000,
    adBrand: 'Nike',
    adCtaText: 'Shop Now',
    createdAt: new Date(Date.now() - 17 * 60 * 60 * 1000).toISOString(),
  },

  {
    id: 's18',
    type: 'regular' as const,
    userId: '1',
    user: MOCK_USERS[0],
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e',
    caption: 'Ultimate productivity hacks 📱',
    tags: ['productivity', 'lifehacks'],
    soundName: 'Focus Mode',
    soundAuthor: 'Productivity Pro',
    likes: 7100,
    comments: 119,
    shares: 41,
    views: 9400,
    bookmarks: 73,
    isLiked: false,
    isBookmarked: false,
    createdAt: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 's19',
    type: 'regular' as const,
    userId: '2',
    user: MOCK_USERS[1],
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80',
    caption: 'Pet care tips every owner should know 🐶',
    tags: ['pets', 'animals'],
    soundName: 'Pet Love',
    soundAuthor: 'Animal Friends',
    likes: 6400,
    comments: 108,
    shares: 35,
    views: 8800,
    bookmarks: 58,
    isLiked: false,
    isBookmarked: true,
    createdAt: new Date(Date.now() - 19 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 's20',
    type: 'regular' as const,
    userId: '1',
    user: MOCK_USERS[0],
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1',
    caption: 'Amazing transformation ✨',
    tags: ['transformation', 'beforeafter'],
    soundName: 'Epic Transition',
    soundAuthor: 'Transition Masters',
    likes: 9200,
    comments: 178,
    shares: 62,
    views: 11800,
    bookmarks: 94,
    isLiked: true,
    isBookmarked: false,
    createdAt: new Date(Date.now() - 20 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 's21',
    type: 'regular' as const,
    userId: '2',
    user: MOCK_USERS[1],
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb',
    caption: 'Street style inspiration 🔥',
    tags: ['streetstyle', 'fashion'],
    soundName: 'Urban Vibes',
    soundAuthor: 'Street Beats',
    likes: 7800,
    comments: 142,
    shares: 48,
    views: 10200,
    bookmarks: 76,
    isLiked: false,
    isBookmarked: false,
    createdAt: new Date(Date.now() - 21 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 's22',
    type: 'regular' as const,
    userId: '1',
    user: MOCK_USERS[0],
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df',
    caption: 'Relaxing nature sounds 🌿',
    tags: ['nature', 'relaxation'],
    soundName: 'Forest Ambiance',
    soundAuthor: 'Nature Sounds',
    likes: 5300,
    comments: 89,
    shares: 26,
    views: 7900,
    bookmarks: 51,
    isLiked: false,
    isBookmarked: true,
    createdAt: new Date(Date.now() - 22 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 's23',
    type: 'regular' as const,
    userId: '2',
    user: MOCK_USERS[1],
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2',
    caption: 'Night routine essentials 🌙',
    tags: ['nightroutine', 'selfcare'],
    soundName: 'Nighttime Calm',
    soundAuthor: 'Relaxation FM',
    likes: 6700,
    comments: 114,
    shares: 37,
    views: 9300,
    bookmarks: 68,
    isLiked: false,
    isBookmarked: false,
    createdAt: new Date(Date.now() - 23 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 's24',
    type: 'regular' as const,
    userId: '1',
    user: MOCK_USERS[0],
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e',
    caption: 'Morning coffee ritual ☕',
    tags: ['coffee', 'morning'],
    soundName: 'Morning Brew',
    soundAuthor: 'Coffee Vibes',
    likes: 6100,
    comments: 103,
    shares: 32,
    views: 8500,
    bookmarks: 59,
    isLiked: false,
    isBookmarked: false,
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 's25',
    type: 'regular' as const,
    userId: '2',
    user: MOCK_USERS[1],
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1502823403499-6ccfcf4fb453',
    caption: 'Adventure awaits 🏔️',
    tags: ['adventure', 'outdoors'],
    soundName: 'Epic Adventure',
    soundAuthor: 'Outdoor Vibes',
    likes: 7900,
    comments: 136,
    shares: 47,
    views: 10400,
    bookmarks: 75,
    isLiked: true,
    isBookmarked: false,
    createdAt: new Date(Date.now() - 25 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 's26-ad',
    type: 'ad' as const,
    userId: 'brand-apple',
    user: {
      id: 'brand-apple',
      username: 'apple',
      email: 'marketing@apple.com',
      avatar: 'https://images.unsplash.com/photo-1611472173362-3f53dbd65d80',
      bio: 'Think Different',
      isVerified: true,
      isMinor: false,
      followers: 15000000,
      following: 0,
      totalViews: 0,
      createdAt: new Date().toISOString(),
    },
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1611472173362-3f53dbd65d80',
    caption: 'Discover the new iPhone',
    tags: ['sponsored', 'tech'],
    likes: 0,
    comments: 0,
    shares: 0,
    views: 156000,
    bookmarks: 0,
    isLiked: false,
    isBookmarked: false,
    adDuration: 15000,
    adMinViewTime: 2000,
    adBrand: 'Apple',
    adCtaText: 'Learn More',
    createdAt: new Date(Date.now() - 26 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 's27',
    type: 'regular' as const,
    userId: '1',
    user: MOCK_USERS[0],
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9',
    caption: 'Best coffee recipes ☕',
    tags: ['coffee', 'recipes'],
    soundName: 'Coffee Shop',
    soundAuthor: 'Café Sounds',
    likes: 8100,
    comments: 151,
    shares: 44,
    views: 10700,
    bookmarks: 81,
    isLiked: true,
    isBookmarked: false,
    createdAt: new Date(Date.now() - 27 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 's28',
    type: 'regular' as const,
    userId: '2',
    user: MOCK_USERS[1],
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1520813792240-56fc4a3765a7',
    caption: 'Yoga for beginners 🧘',
    tags: ['yoga', 'wellness'],
    soundName: 'Zen Mode',
    soundAuthor: 'Meditation Music',
    likes: 7400,
    comments: 128,
    shares: 41,
    views: 9800,
    bookmarks: 72,
    isLiked: false,
    isBookmarked: true,
    createdAt: new Date(Date.now() - 28 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 's29',
    type: 'regular' as const,
    userId: '1',
    user: MOCK_USERS[0],
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f',
    caption: 'Thrift shopping haul 🛍️',
    tags: ['thrifting', 'shopping'],
    soundName: 'Shopping Spree',
    soundAuthor: 'Retail Therapy',
    likes: 6900,
    comments: 119,
    shares: 39,
    views: 9100,
    bookmarks: 64,
    isLiked: false,
    isBookmarked: false,
    createdAt: new Date(Date.now() - 29 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 's30',
    type: 'regular' as const,
    userId: '2',
    user: MOCK_USERS[1],
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1502823403499-6ccfcf4fb453',
    caption: 'City nightlife vibes 🌃',
    tags: ['nightlife', 'city'],
    soundName: 'City Nights',
    soundAuthor: 'Urban Sounds',
    likes: 8600,
    comments: 147,
    shares: 52,
    views: 11100,
    bookmarks: 87,
    isLiked: true,
    isBookmarked: false,
    createdAt: new Date(Date.now() - 30 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 's31',
    type: 'regular' as const,
    userId: '1',
    user: MOCK_USERS[0],
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d',
    caption: 'Quick study tips 📚',
    tags: ['study', 'education'],
    soundName: 'Focus Time',
    soundAuthor: 'Study Beats',
    likes: 5800,
    comments: 96,
    shares: 29,
    views: 8200,
    bookmarks: 56,
    isLiked: false,
    isBookmarked: false,
    createdAt: new Date(Date.now() - 31 * 60 * 60 * 1000).toISOString(),
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'n1',
    type: 'like',
    user: MOCK_USERS[0],
    shortId: 's1',
    thumbnailUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330',
    text: 'liked your Short',
    createdAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    isRead: false,
  },
  {
    id: 'n2',
    type: 'comment',
    user: MOCK_USERS[1],
    shortId: 's2',
    thumbnailUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d',
    text: 'commented on your Short',
    commentText: 'This is amazing! 🔥',
    createdAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    isRead: false,
  },
  {
    id: 'n3',
    type: 'share',
    user: MOCK_USERS[0],
    shortId: 's3',
    thumbnailUrl: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e',
    text: 'shared your Short',
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    isRead: true,
  },
  {
    id: 'n4',
    type: 'mention',
    user: MOCK_USERS[1],
    shortId: 's4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80',
    text: 'mentioned you in a Short',
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    isRead: true,
  },
  {
    id: 'n5',
    type: 'reply',
    user: MOCK_USERS[0],
    shortId: 's1',
    thumbnailUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330',
    text: 'replied to your comment',
    commentText: 'Thanks for the support!',
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    isRead: true,
  },
  {
    id: 'n6',
    type: 'like',
    user: MOCK_USERS[1],
    shortId: 's5-membership',
    thumbnailUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1',
    text: 'liked your Short',
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    isRead: true,
  },
  {
    id: 'n7',
    type: 'comment',
    user: MOCK_USERS[0],
    shortId: 's6',
    thumbnailUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb',
    text: 'commented on your Short',
    commentText: 'Great content! Keep it up 💪',
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    isRead: true,
  },
  {
    id: 'n8',
    type: 'share',
    user: MOCK_USERS[1],
    shortId: 's7',
    thumbnailUrl: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df',
    text: 'shared your Short',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    isRead: true,
  },
  {
    id: 'n9',
    type: 'mention',
    user: MOCK_USERS[0],
    shortId: 's8',
    thumbnailUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2',
    text: 'mentioned you in a comment',
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    isRead: true,
  },
];

export const SHOP_CATEGORIES = ['Clothing', 'Electronics', 'Healthcare', 'Toys', 'Others'] as const;

export const MOCK_PRO_USERS: ProUser[] = [
  {
    id: 'pro1',
    displayName: 'Xbox US',
    username: 'xboxus',
    avatar: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Xbox_one_logo.svg/200px-Xbox_one_logo.svg.png',
    isVerified: true,
    isPro: true,
    totalViews: 149500000,
    products: [
      {
        id: 'p1',
        name: 'Classic Bullhead Shirt Toys',
        price: 60,
        image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400',
        brand: 'Zara',
        views: 12500,
        isFavorited: true,
        isBookmarked: true,
        category: 'Clothing',
      },
      {
        id: 'p2',
        name: 'Premium Gaming Headset',
        price: 120,
        image: 'https://images.unsplash.com/photo-1599669454699-248893623440?w=400',
        brand: 'Xbox',
        views: 8900,
        isFavorited: false,
        isBookmarked: true,
        category: 'Electronics',
      },
      {
        id: 'p3',
        name: 'Wireless Controller',
        price: 75,
        image: 'https://images.unsplash.com/photo-1592840496694-26d035b52b48?w=400',
        brand: 'Xbox',
        views: 15600,
        isFavorited: true,
        isBookmarked: false,
        category: 'Electronics',
      },
    ],
  },
  {
    id: 'pro2',
    displayName: 'UFC',
    username: 'therealufc',
    avatar: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/UFC_Logo.svg/200px-UFC_Logo.svg.png',
    isVerified: true,
    isPro: true,
    totalViews: 85600000,
    products: [
      {
        id: 'p4',
        name: 'Classic Bullhead Shirt',
        price: 60,
        image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400',
        brand: 'Zara',
        views: 12500,
        isFavorited: true,
        isBookmarked: true,
        category: 'Clothing',
      },
      {
        id: 'p5',
        name: 'UFC Training Gloves',
        price: 89,
        image: 'https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?w=400',
        brand: 'UFC',
        views: 9800,
        isFavorited: false,
        isBookmarked: false,
        category: 'Others',
      },
      {
        id: 'p6',
        name: 'Championship Belt Replica',
        price: 250,
        image: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=400',
        brand: 'UFC',
        views: 7200,
        isFavorited: true,
        isBookmarked: true,
        category: 'Others',
      },
    ],
  },
  {
    id: 'pro3',
    displayName: 'Netflix',
    username: 'netflixoriginal',
    avatar: 'https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?w=400',
    isVerified: true,
    isPro: true,
    totalViews: 34500000,
    products: [
      {
        id: 'p7',
        name: 'Stranger Things Hoodie',
        price: 85,
        image: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=400',
        brand: 'Netflix',
        views: 18900,
        isFavorited: true,
        isBookmarked: false,
        category: 'Clothing',
      },
      {
        id: 'p8',
        name: 'Wednesday Plush Toy',
        price: 35,
        image: 'https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=400',
        brand: 'Netflix',
        views: 14200,
        isFavorited: false,
        isBookmarked: true,
        category: 'Toys',
      },
    ],
  },
];

export const MOCK_NON_PRO_USERS = [
  {
    id: 'np1',
    displayName: 'Rachel',
    username: 'rachel_style',
    avatar: 'https://i.pravatar.cc/150?img=5',
    isVerified: false,
    isPro: false,
    totalViews: 8500,
  },
];

export const SEARCH_ACCOUNTS = [
  {
    id: 'sa1',
    displayName: 'Xbox US',
    username: 'xboxus',
    avatar: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Xbox_one_logo.svg/200px-Xbox_one_logo.svg.png',
    isVerified: true,
    isPro: true,
    totalViews: 149500000,
    isFollowing: false,
  },
  {
    id: 'sa2',
    displayName: 'UFC',
    username: 'therealufc',
    avatar: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/UFC_Logo.svg/200px-UFC_Logo.svg.png',
    isVerified: true,
    isPro: true,
    totalViews: 85600000,
    isFollowing: false,
  },
  {
    id: 'sa3',
    displayName: 'Netflix',
    username: 'netflixoriginal',
    avatar: 'https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?w=400',
    isVerified: true,
    isPro: true,
    totalViews: 34500000,
    isFollowing: false,
  },
  {
    id: 'sa4',
    displayName: 'Rachel',
    username: 'rachel_style',
    avatar: 'https://i.pravatar.cc/150?img=5',
    isVerified: false,
    isPro: false,
    totalViews: 8500,
    isFollowing: false,
  },
  {
    id: 'sa5',
    displayName: 'Apple',
    username: 'apple',
    avatar: 'https://images.unsplash.com/photo-1611472173362-3f53dbd65d80?w=400',
    isVerified: true,
    isPro: true,
    totalViews: 256000000,
    isFollowing: true,
  },
  {
    id: 'sa6',
    displayName: 'Nike',
    username: 'nike',
    avatar: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400',
    isVerified: true,
    isPro: true,
    totalViews: 178000000,
    isFollowing: false,
  },
  {
    id: 'sa7',
    displayName: 'Emma Creates',
    username: 'emma_creates',
    avatar: 'https://i.pravatar.cc/150?img=1',
    isVerified: true,
    isPro: false,
    totalViews: 5600000,
    isFollowing: true,
  },
  {
    id: 'sa8',
    displayName: 'Alex Vibes',
    username: 'alex_vibes',
    avatar: 'https://i.pravatar.cc/150?img=12',
    isVerified: false,
    isPro: false,
    totalViews: 1200000,
    isFollowing: false,
  },
];

export const LIVE_STREAMS = [
  {
    id: 'l1',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475',
    viewers: 12500,
    category: 'Technology',
  },
  {
    id: 'l2',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1461988320302-91bde64fc8e4',
    viewers: 8900,
    category: 'Technology',
  },
  {
    id: 'l3',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1511367461989-f85a21fda167',
    viewers: 23400,
    category: 'Music',
  },
  {
    id: 'l4',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55',
    viewers: 15600,
    category: 'Sports',
  },
  {
    id: 'l5',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce',
    viewers: 9800,
    category: 'Fashion',
  },
  {
    id: 'l6',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5',
    viewers: 6700,
    category: 'Technology',
  },
  {
    id: 'l7',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836',
    viewers: 18900,
    category: 'Food',
  },
  {
    id: 'l8',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0',
    viewers: 14500,
    category: 'Politics',
  },
  {
    id: 'l9',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1493711662062-fa541adb3fc8',
    viewers: 11200,
    category: 'Travel',
  },
  {
    id: 'l10',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e',
    viewers: 20300,
    category: 'Gaming',
  },
  {
    id: 'l11',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1488590528505-98d2b5aba04b',
    viewers: 17800,
    category: 'Technology',
  },
  {
    id: 'l12',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475',
    viewers: 9200,
    category: 'Fashion',
  },
];

export const DISCOVER_VIDEOS = [
  {
    id: '1',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475',
    views: 125000,
    category: 'Technology',
  },
  {
    id: '2',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1461988320302-91bde64fc8e4',
    views: 89000,
    category: 'Technology',
  },
  {
    id: '3',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1511367461989-f85a21fda167',
    views: 234000,
    category: 'Music',
  },
  {
    id: '4',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55',
    views: 156000,
    category: 'Sports',
  },
  {
    id: '5',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce',
    views: 98000,
    category: 'Fashion',
  },
  {
    id: '6',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5',
    views: 67000,
    category: 'Technology',
  },
  {
    id: '7',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836',
    views: 189000,
    category: 'Food',
  },
  {
    id: '8',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0',
    views: 145000,
    category: 'Politics',
  },
  {
    id: '9',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1493711662062-fa541adb3fc8',
    views: 112000,
    category: 'Travel',
  },
  {
    id: '10',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e',
    views: 203000,
    category: 'Gaming',
  },
  {
    id: '11',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1488590528505-98d2b5aba04b',
    views: 178000,
    category: 'Technology',
  },
  {
    id: '12',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475',
    views: 92000,
    category: 'Fashion',
  },
  {
    id: '13',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745',
    views: 256000,
    category: 'Music',
  },
  {
    id: '14',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1517649763962-0c623066013b',
    views: 143000,
    category: 'Sports',
  },
  {
    id: '15',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1540553016722-983e48a2cd10',
    views: 87000,
    category: 'Travel',
  },
  {
    id: '16',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836',
    views: 215000,
    category: 'Food',
  },
  {
    id: '17',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1569091491550-5e8d8b2b8a06',
    views: 167000,
    category: 'Politics',
  },
  {
    id: '18',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1511512578047-dfb367046420',
    views: 198000,
    category: 'Gaming',
  },
  {
    id: '19',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2',
    views: 134000,
    category: 'Technology',
  },
  {
    id: '20',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1483985988355-763728e1935b',
    views: 276000,
    category: 'Fashion',
  },
  {
    id: '21',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f',
    views: 156000,
    category: 'Music',
  },
  {
    id: '22',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211',
    views: 89500,
    category: 'Sports',
  },
  {
    id: '23',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1',
    views: 234500,
    category: 'Travel',
  },
  {
    id: '24',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38',
    views: 187000,
    category: 'Food',
  },
  {
    id: '25',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1',
    views: 145600,
    category: 'Politics',
  },
  {
    id: '26',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1552820728-8b83bb6b773f',
    views: 267000,
    category: 'Gaming',
  },
  {
    id: '27',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c',
    views: 123000,
    category: 'Technology',
  },
  {
    id: '28',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1485965120184-e220f721d03e',
    views: 198500,
    category: 'Fashion',
  },
  {
    id: '29',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819',
    views: 176000,
    category: 'Music',
  },
  {
    id: '30',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd',
    views: 234000,
    category: 'Sports',
  },
  {
    id: '31',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1488646953014-85cb44e25828',
    views: 156700,
    category: 'Travel',
  },
  {
    id: '32',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836',
    views: 289000,
    category: 'Food',
  },
  {
    id: '33',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1432821596592-e2c18b78144f',
    views: 178900,
    category: 'Politics',
  },
  {
    id: '34',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1511512578047-dfb367046420',
    views: 245000,
    category: 'Gaming',
  },
  {
    id: '35',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1487014679447-9f8336841d58',
    views: 134500,
    category: 'Technology',
  },
  {
    id: '36',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1558769132-cb1aea3c1d42',
    views: 167800,
    category: 'Fashion',
  },
  {
    id: '37',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1511379938547-c1f69419868d',
    views: 223000,
    category: 'Music',
  },
  {
    id: '38',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64',
    views: 189600,
    category: 'Sports',
  },
  {
    id: '39',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4',
    views: 256700,
    category: 'Travel',
  },
  {
    id: '40',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd',
    views: 198300,
    category: 'Food',
  },
  {
    id: '41',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1529612700005-e35377bf1415',
    views: 176500,
    category: 'Politics',
  },
  {
    id: '42',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f',
    views: 234800,
    category: 'Gaming',
  },
  {
    id: '43',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    thumbnailUrl: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085',
    views: 287000,
    category: 'Technology',
  },
];
