import { StyleSheet } from "react-native";
import colors from "@/constants/colors";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.black,
  },
  safeArea: {
    backgroundColor: "transparent",
  },
  headerBlur: {
    backgroundColor: colors.surfaceBlur,
  },
  header: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    paddingHorizontal: 12,
    paddingVertical: 8,
    gap: 12,
  },
  backButton: {
    width: 40,
    height: 40,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    backgroundColor: colors.whiteOpacity08,
    borderRadius: 100,
  },
  headerCenter: {
    flex: 1,
    marginLeft: 4,
  },
  headerTitleRow: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    gap: 8,
  },
  headerOnlineDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: "rgba(100, 205, 117, 1)",
  },
  headerName: {
    fontSize: 18,
    fontWeight: "700" as const,
    fontFamily: "Poppins_500Medium",
    color: colors.white,
  },
  headerUsername: {
    fontSize: 12,
    color: colors.whiteOpacity48,
    marginTop: 2,
    fontFamily: "Poppins_400Regular",
  },
  settingsButton: {
    width: 40,
    height: 40,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    backgroundColor: colors.whiteOpacity08,
    borderRadius: 100,
  },
  messagesContent: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 16,
  },
  systemMessageContainer: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    marginVertical: 16,
    gap: 12,
  },
  systemLine: {
    flex: 1,
    height: 1,
    backgroundColor: colors.whiteOpacity12,
  },
  systemMessageText: {
    fontSize: 13,
    color: colors.whiteOpacity48,
    fontFamily: "Poppins_400Regular",
  },
  statusMessageContainer: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    marginVertical: 16,
    gap: 12,
  },
  statusLine: {
    flex: 1,
    height: 1,
    backgroundColor: colors.whiteOpacity12,
  },
  statusMessageText: {
    fontSize: 13,
    color: colors.whiteOpacity48,
    fontFamily: "Poppins_400Regular",
  },
  dateSeparator: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    marginVertical: 16,
    gap: 12,
  },
  dateLine: {
    flex: 1,
    height: 1,
    backgroundColor: colors.whiteOpacity12,
  },
  dateContainer: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    gap: 4,
    backgroundColor: colors.whiteOpacity04,
    borderRadius: 100,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  dateText: {
    fontSize: 12,
    fontWeight: "500" as const,
    fontFamily: "Poppins_500Medium",
    color: colors.whiteOpacity48,
  },
  myMessageWrapper: {
    alignSelf: "flex-end" as const,
    maxWidth: "80%",
    marginBottom: 12,
  },
  myMessageBubble: {
    backgroundColor: colors.gray3,
    borderRadius: 16,
    borderBottomRightRadius: 4,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  myMessageText: {
    fontSize: 15,
    lineHeight: 22,
    color: colors.white,
    fontFamily: "Poppins_400Regular",
  },
  myTimestampRow: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    justifyContent: "flex-end" as const,
    marginTop: 6,
    gap: 4,
  },
  myTimestamp: {
    fontSize: 11,
    color: colors.whiteOpacity48,
    fontFamily: "Poppins_400Regular",
  },
  timestampDivider: {
    fontSize: 11,
    color: "rgba(255,255,255,0.32)",
    marginHorizontal: 2,
  },
  theirMessageWrapper: {
    alignSelf: "flex-start" as const,
    maxWidth: "80%",
    marginBottom: 12,
  },
  senderRow: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    gap: 6,
    marginBottom: 6,
    backgroundColor: "rgba(255, 255, 255, 0.04)",
    alignSelf: "flex-start",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
  },
  senderOnlineDot: {
    width: 12,
    height: 12,
    borderRadius: 12,
    backgroundColor: "rgba(57, 112, 80, 1)",
  },
  senderName: {
    fontSize: 13,
    fontWeight: "500" as const,
    fontFamily: "Poppins_500Medium",
    color: colors.white,
  },
  theirMessageBubble: {
    backgroundColor: colors.gray3,
    borderRadius: 16,
    borderBottomLeftRadius: 4,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  theirMessageText: {
    fontSize: 15,
    lineHeight: 22,
    color: colors.white,
    fontFamily: "Poppins_400Regular",
  },
  actionsRow: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    marginTop: 8,
    gap: 4,
  },
  actionButton: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    backgroundColor: colors.whiteOpacity08,
    borderRadius: 16,
    paddingHorizontal: 10,
    paddingVertical: 6,
    gap: 4,
  },
  actionText: {
    fontSize: 12,
    color: colors.whiteOpacity64,
    fontFamily: "Poppins_400Regular",
  },
  actionIconButton: {
    width: 28,
    height: 28,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    backgroundColor: colors.whiteOpacity08,
    borderRadius: 14,
  },
  translateText: {
    fontSize: 12,
    marginTop: 8,
    fontFamily: "Poppins_500Medium",
  },
  voiceMessageBubble: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    backgroundColor: colors.gray3,
    borderRadius: 24,
    paddingHorizontal: 8,
    paddingVertical: 8,
    gap: 8,
  },
  playButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.whiteOpacity16,
    alignItems: "center" as const,
    justifyContent: "center" as const,
  },
  waveformContainer: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    gap: 2,
    height: 24,
  },
  waveformBar: {
    width: 3,
    backgroundColor: colors.white,
    borderRadius: 2,
  },
  speedButton: {
    backgroundColor: colors.whiteOpacity16,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  speedText: {
    fontSize: 12,
    fontWeight: "600" as const,
    fontFamily: "Poppins_600SemiBold",
    color: colors.white,
  },
  theirVoiceMessageBubble: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    backgroundColor: colors.gray3,
    borderRadius: 24,
    paddingHorizontal: 8,
    paddingVertical: 8,
    gap: 8,
  },
  theirPlayButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.whiteOpacity16,
    alignItems: "center" as const,
    justifyContent: "center" as const,
  },
  theirSpeedButton: {
    backgroundColor: colors.whiteOpacity16,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  theirSpeedText: {
    fontSize: 12,
    fontWeight: "600" as const,
    fontFamily: "Poppins_600SemiBold",
    color: colors.white,
  },
  inputBlur: {
    backgroundColor: colors.surfaceBlur,
  },
  inputSafeArea: {
    backgroundColor: "transparent",
  },
  inputContainer: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    paddingHorizontal: 12,
    paddingVertical: 12,
    gap: 8,
  },
  iconButton: {
    width: 40,
    height: 40,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    backgroundColor: colors.whiteOpacity08,
    borderRadius: 100,
  },
  inputWrapperContainer: {
    flex: 1,
  },
  inputWrapper: {
    height: 44,
    backgroundColor: colors.black,
    borderRadius: 100,
    paddingHorizontal: 16,
    justifyContent: "center" as const,
  },
  replyPreview: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    backgroundColor: colors.whiteOpacity08,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginBottom: 8,
  },
  replyPreviewContent: {
    flex: 1,
  },
  replyPreviewLabel: {
    fontSize: 11,
    color: colors.whiteOpacity48,
    marginBottom: 2,
    fontFamily: "Poppins_400Regular",
  },
  replyPreviewText: {
    fontSize: 13,
    color: colors.white,
    fontFamily: "Poppins_400Regular",
  },
  cancelReplyButton: {
    width: 24,
    height: 24,
    alignItems: "center" as const,
    justifyContent: "center" as const,
  },
  cancelReplyText: {
    fontSize: 20,
    color: colors.whiteOpacity48,
  },
  recordingButton: {
    backgroundColor: "rgba(238, 16, 69, 0.2)",
  },
  input: {
    fontSize: 14,
    color: colors.white,
    paddingTop: 0,
    paddingBottom: 0,
    fontFamily: "Poppins_400Regular",
  },
  sendButton: {
    width: 44,
    height: 44,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    borderRadius: 100,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: "flex-end" as const,
  },
  modalBackground: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0, 0, 0, 0.7)",
  },
  settingsSheet: {
    backgroundColor: colors.gray1,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingBottom: 34,
  },
  settingsContent: {
    paddingHorizontal: 16,
    paddingTop: 24,
  },
  settingsUserSection: {
    alignItems: "center" as const,
    marginBottom: 24,
  },
  settingsAvatar: {
    width: 80,
    height: 80,
    borderRadius: 40,
    marginBottom: 12,
  },
  settingsUserName: {
    fontSize: 20,
    fontWeight: "700" as const,
    color: colors.white,
    marginBottom: 4,
  },
  settingsUsername: {
    fontSize: 14,
    color: colors.whiteOpacity48,
  },
  settingsOptions: {
    gap: 8,
    marginBottom: 16,
  },
  settingsOption: {
    backgroundColor: colors.whiteOpacity08,
    borderRadius: 12,
    paddingVertical: 16,
    paddingHorizontal: 16,
  },
  settingsOptionText: {
    fontSize: 16,
    fontWeight: "500" as const,
    fontFamily: "Poppins_500Medium",
    color: colors.white,
  },
  settingsOptionTextDanger: {
    fontSize: 16,
    fontWeight: "500" as const,
    fontFamily: "Poppins_500Medium",
    color: colors.error,
  },
  cancelButton: {
    borderWidth: 1,
    borderColor: colors.gold,
    borderRadius: 100,
    paddingVertical: 14,
    alignItems: "center" as const,
    marginTop: 8,
  },
  cancelButtonText: {
    fontSize: 16,
    fontWeight: "600" as const,
    fontFamily: "Poppins_600SemiBold",
    color: colors.gold,
  },
  imageMessage: {
    width: 200,
    height: 200,
    borderRadius: 12,
  },

  videoWrapper: {
    width: 220,
    height: 260,
    borderRadius: 12,
    overflow: "hidden",
  },

  video: {
    width: "100%",
    height: "100%",
    borderRadius: 12,
    overflow: "hidden",
  },

  voiceBubble: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: "#2A2A2A",
    borderRadius: 20,
  },

  messageText: {
    color: "#FFF",
    fontSize: 16,
  },
  mediaImage: {
    width: 164,
    height: 164,
    borderRadius: 14,
    overflow: "hidden",
  },

  videoContainer: {
    padding: 2,
    borderRadius: 14,
    overflow: "hidden",

    backgroundColor: "#FFFFFF29",
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
  },

  myMedia: {
    alignSelf: "flex-end",
  },

  theirMedia: {
    alignSelf: "flex-start",
  },
  videoOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: "center",
    alignItems: "center",
  },

  playPauseButton: {
    width: 50,
    height: 50,
    borderRadius: 28,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
});
